### ISSUE TITLE
minimum duplicate in schema file

### ISSUE THREAD

**Issue by tobimx** [tomcollins/json-schema-static-docs#108]
https://github.com/tomcollins/json-schema-static-docs/blob/master/templates/schema.hbs#L181-L183
is duplicate to 
https://github.com/tomcollins/json-schema-static-docs/blob/master/templates/schema.hbs#L202-L204

**Comment by tomcollins** [comment]
Hi @tobimx. Thanks for reporting this. Will get it fixed ASAP. Apologies for the slow response.
