### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by Jazcash** [tomcollins/json-schema-static-docs#113]
Seems to be because of this code:
```js
const inputPathGlob = path.join(
    this._options.inputPath,
    this._options.inputFileGlob
  );
```
Which converts `schema/**/*.{yml,json}` into `schema\**\*.{yml,json}`, and `fast-glob` [states to always pass forward slashes](https://www.npmjs.com/package/fast-glob#user-content-how-to-write-patterns-on-windows). If I add `.replace(/\\/g, '/')` to the end of that code then it works fine.

**Comment by Xenoage** [comment]
I can confirm this fixes the problem on Windows!

**Comment by AceOfWands** [comment]
In order to follow the instruction of fast-glob team, we need to replace
```
const inputPathGlob = path.join(
  this._options.inputPath,
  this._options.inputFileGlob
);
```
with

```
const inputPathPattern = fastGlob.convertPathToPattern(
  this._options.inputPath
);
const inputPathGlob = `${inputPathPattern}/${this._options.inputFileGlob}`;
```
where `fastGlob` is imported by `const fastGlob = require("fast-glob")`

**Comment by rthm93** [comment]
> In order to follow the instruction of fast-glob team, we need to replace
> 
> ```
> const inputPathGlob = path.join(
>   this._options.inputPath,
>   this._options.inputFileGlob
> );
> ```
> 
> with
> 
> ```
> const inputPathPattern = fastGlob.convertPathToPattern(
>   this._options.inputPath
> );
> const inputPathGlob = `${inputPathPattern}/${this._options.inputFileGlob}`;
> ```
> 
> where `fastGlob` is imported by `const fastGlob = require("fast-glob")`
> 
> [https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows](url)

This solution worked on Windows machine.

**Comment by donalfenwick-planet** [comment]
@tomcollins - I think there is still an issue here with the globbing in windows.

Tried generating files with the example script provided and I get 0 files detected in windows.
![image](https://github.com/tomcollins/json-schema-static-docs/assets/107054430/d968bc82-afa5-4609-b298-fe38bb318b75)

However running the exact same script in WSL the globbing detects json schema files.
![image](https://github.com/tomcollins/json-schema-static-docs/assets/107054430/9a3f6f63-7260-4715-93e0-cdcd95d98ade)

Running the following script with node 20.10.0 in both instances

```javascript 
const JsonSchemaStaticDocs = require("json-schema-static-docs");

(async () => {
  let jsonSchemaStaticDocs = new JsonSchemaStaticDocs({
    inputPath: "contracts",
    outputPath: "./output",
    ajvOptions: {
      allowUnionTypes: true,
    },
  });
  await jsonSchemaStaticDocs.generate();
  console.log("Documents generated.");
})();
```

**Comment by edemartel** [comment]
Yeah, you can't feed the output of `path.join` to fast-glob as that generates path with the native path separator, which is a backslash on Windows, and then fast-glob explicitly requires slashes are path separators.

So, you do `convertPathToPattern`, which is nice, but then you immediately ruin it by feeding that back into `path.join`. Use use slashes everywhere.
