### ISSUE TITLE
isRequired not available on child properties.

### ISSUE THREAD

**Issue by mattbryson** [tomcollins/json-schema-static-docs#54]
Hi,

Great doc generator, far cleaner than most of them!  

However I don't think the merged property `isRequired` is being set for nested properties.

Take this for example :

```json
{
  "type": "object",
  "properties": {
    "one": { 
       "type": "object" 
    },
    "two": { 
        "type": "object",
         "required": [
            "nestedProperty"
           ],
        "properties": {
           "nestedProperty": {
               "type": "string"
            }
         }
     }
}
```        

If you print out `isRequired` for the top properties "one" or "two" it's "false" as expected.

If you print out `isRequired` for the nested property "two.nestedProperty" it's an empty value/undefined, where it should be true.

cheers

m

**Comment by tomcollins** [comment]
Hi @mattbryson,

Glad you like the library. I've made a quick fix to set isRequired on child properties when merging. 

It should really do this recursively so isRequired is set on all child properties of all objects. But that isn't done in this initial change.

I've also improved (I hope) the template for rendering not $ref child properties of objects, which is related to this sort of scenario.
