### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by iwyrkore** [tomcollins/json-schema-static-docs#55]
Is there a license for this code?

**Comment by tomcollins** [comment]
Hi @iwyrkore.

I've just added a licence: GNU General Public License v3.0

Released in v0.14.0
https://github.com/tomcollins/json-schema-static-docs/releases/tag/v0.14.0

Apologies for the slow response to this.

**Comment by tomcollins** [comment]
Closing as LICENCE has been added
