### ISSUE TITLE
The index.md is broken because the links in it are .html instead of the output .md

### ISSUE THREAD

**Issue by radleta** [tomcollins/json-schema-static-docs#97]
The below two lines cause the index.md to be broken since they are converting the links to .HTML instead of leaving them as .md.

https://github.com/tomcollins/json-schema-static-docs/blob/475a4d4370a6da1c06f473185c4ca9eb29bd52be/lib/renderer/index.js#L16
https://github.com/tomcollins/json-schema-static-docs/blob/475a4d4370a6da1c06f473185c4ca9eb29bd52be/lib/renderer/index.js#L17

**Comment by tomcollins** [comment]
Hi @radleta . Thanks for raising the issue, I agree that this is the incorrect behaviour. I've fixed this in #98 and released as 0.22.2. 

Let me know if you still have a problem.

**Comment by radleta** [comment]
Thanks! 👍
